server:
  port: 2333 # Lavalinkがリッスンするポート (config.yamlと合わせる)
  address: 0.0.0.0
lavalink:
  server:
    password: "hogefugapiyoyo" # Lavalinkのパスワード (config.yamlと合わせる)
    sources: # 利用する音源ソース
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true # ニコニコ動画などの直接URL再生に重要
      local: false
    # yt-dlp (または youtube-dl) のパスを明示的に指定する必要がある場合
    # ytdlPath: "/path/to/yt-dlp" # もしLavalinkがyt-dlpを見つけられない場合
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # プレイリストから一度に読み込む曲数
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
# Logging levels
logging:
  level:
    root: INFO
    lavalink: INFO