server:
  port: 2333 # .envのLAVALINK_PORTと合わせる
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass" # .envのLAVALINK_PASSWORDと合わせる
    sources: # 利用する音源ソース
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false # ローカルファイル再生を許可する場合はtrue
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # YouTubeプレイリストの読み込みページ数上限
    # Spotify連携 (別途Spotify Developerでアプリ登録が必要)
    # spotify:
    #   clientId: "YOUR_SPOTIFY_CLIENT_ID"
    #   clientSecret: "YOUR_SPOTIFY_CLIENT_SECRET"
    #   countryCode: "JP" # Spotifyの地域コード
logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO